from otp.speedchat.SCCustomTerminal import SCCustomMsgEvent
from otp.speedchat.SCEmoteTerminal import SCEmoteMsgEvent, SCEmoteNoAccessEvent
from otp.speedchat.SCStaticTextTerminal import SCStaticTextMsgEvent
from otp.speedchat.SCTerminal import SCTerminalLinkedEmoteEvent, SCTerminalSelectedEvent

