from otp.distributed.OtpDoGlobals import *

netMessages = [
    'districtStatus',
    'queryDistrictStatus',
    'registerShard',
    'startHoliday',
    'stopHoliday',
    'uberDOGHolidayStarted',
    'uberDOGHolidayEnded',
    'publishException',
    'publishHacker',
    'hasInventory',
    'addInventory',
    'removeInventory',
    'getInventory',
    'hasInventoryResponse',
    'getInventoryResponse',
    'b_setAccumulators',
    'b_setAccumulator',
    'b_setStackLimits',
    'b_setStacks',
    'b_setStack',
    'b_setOwnerId',
    'getAccumulators',
    'getAccumulator',
    'getStackLimit',
    'getStack',
    'getOwnerId',
    'getOwnerIdResponse',
    'getAccumulatorsResponse'
    'getAccumulatorResponse',
    'getStackLimitResponse',
    'getStackResponse'
]